apiVersion: v1
kind: PersistentVolume
metadata:
  name: Internal-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /path-of-nfs-storage
    server: (your-nfs-server-ip-address)
  persistentVolumeReclaimPolicy: Recycle
